"use client";

import { useState, useRef, useCallback, useEffect } from "react";
import { motion, useMotionValue, useSpring, animate } from "framer-motion";
import { useRouter } from "next/navigation";
import { useIsMobile } from "@/hooks/use-mobile";
import { ArrowRight } from "lucide-react";

// Progress bar fill duration in ms
const FILL_DURATION = 7000;
const BROWSER_WIDTH = 700;
// Resting: 50% hidden off-screen right
const RESTING_X = BROWSER_WIDTH * 0.40;
// Hovered: fully visible
const HOVERED_X = BROWSER_WIDTH * 0;

// Single concatenated loop of key feature recordings.
// Generated by: npm run record:shortlist
// Hosted in Supabase Storage (videos bucket) — uploaded via scripts/upload-videos.ts
const HERO_VIDEO = `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/videos/hero-loop.mp4`;

export const HeroBrowser = ({
  onHoverChange,
  ctaHovering,
}: {
  onHoverChange?: (hovering: boolean) => void;
  ctaHovering?: boolean;
}) => {
  const isMobile = useIsMobile();
  const router = useRouter();
  const [selfHovering, setSelfHovering] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);

  // Slide offset as a motion value so we can spring it
  const slideX = useMotionValue(RESTING_X);
  const springX = useSpring(slideX, { stiffness: 200, damping: 24 });

  const isHovered = selfHovering || !!ctaHovering;

  // Pull out or retract based on combined hover state
  useEffect(() => {
    slideX.set(isHovered ? HOVERED_X : RESTING_X);
  }, [isHovered, slideX]);

  // Half speed at rest, full speed when hovered
  useEffect(() => {
    if (videoRef.current) {
      videoRef.current.playbackRate = isHovered ? 1 : 0.5;
    }
  }, [isHovered]);

  const handleEnter = useCallback(() => {
    setSelfHovering(true);
    onHoverChange?.(true);
  }, [onHoverChange]);

  const handleLeave = useCallback(() => {
    setSelfHovering(false);
    onHoverChange?.(false);
  }, [onHoverChange]);

  if (isMobile) return null;

  return (
    <motion.div
      onMouseEnter={handleEnter}
      onMouseLeave={handleLeave}
      onClick={() => router.push("/guides?type=tutorial")}
      className="absolute right-0 top-1/2 z-[5] cursor-pointer"
      style={{
        width: BROWSER_WIDTH,
        x: springX,
        y: "-50%",
      }}
      initial={{ opacity: 0, x: BROWSER_WIDTH }}
      animate={{ opacity: 1, x: RESTING_X }}
      transition={{ type: "spring", stiffness: 80, damping: 18, delay: 0.6 }}
    >
      {/* Browser frame */}
      <div className="relative rounded-xl border border-border/60 bg-card shadow-2xl overflow-hidden">
        {/* Title bar */}
        <div className="flex items-center gap-2 px-4 py-3 bg-muted/80 border-b border-border/40">
          {/* macOS dots */}
          <div className="flex items-center gap-1.5">
            <div className="w-3 h-3 rounded-full bg-[#ff5f57]" />
            <div className="w-3 h-3 rounded-full bg-[#febc2e]" />
            <div className="w-3 h-3 rounded-full bg-[#28c840]" />
          </div>
          {/* Address bar */}
          <div className="flex-1 mx-3">
            <div className="bg-background/60 rounded-md px-3 py-1 text-xs text-muted-foreground font-mono truncate">
              app.useprompt.co.uk/dashboard
            </div>
          </div>
        </div>

        {/* Content area — video preview */}
        <div className="relative aspect-[4/3] bg-background overflow-hidden">
          {/* Video dims slightly at rest */}
          <motion.div
            className="w-full h-full"
            animate={{ opacity: isHovered ? 1 : 0.5 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
          >
            <video
              ref={videoRef}
              src={HERO_VIDEO}
              className="w-full h-full object-cover object-left-top"
              muted
              autoPlay
              loop
              playsInline
            />
          </motion.div>
          {/* Frosted glass overlay — blurs + washes at rest, fades on hover */}
          <motion.div
            className="absolute inset-0 backdrop-blur-[2px] bg-background/0 pointer-events-none"
            animate={{ opacity: isHovered ? 0 : 1 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
          />
          {/* Subtle gradient overlay on the left edge for smooth page blend */}
          <div className="absolute inset-y-0 left-0 w-16 bg-gradient-to-r from-background/40 to-transparent pointer-events-none" />
        </div>
      </div>
    </motion.div>
  );
};

/**
 * CTA buttons: "Watch tutorials" with green progress bar fill + "Try for free".
 * The tutorials button fills green when the browser or itself is hovered.
 * After 3s continuous hover, navigates to /tutorials.
 */
export const HeroCta = ({
  browserHovering,
  onHoverChange,
}: {
  browserHovering: boolean;
  onHoverChange?: (hovering: boolean) => void;
}) => {
  const router = useRouter();
  const [selfHovering, setSelfHovering] = useState(false);
  const hoverStartRef = useRef<number | null>(null);
  const rafRef = useRef<number>(undefined);
  const navigatedRef = useRef(false);

  const progress = useMotionValue(0);
  const smoothProgress = useSpring(progress, { stiffness: 300, damping: 30 });

  const startFill = useCallback(() => {
    if (navigatedRef.current) return;
    if (hoverStartRef.current) return;
    hoverStartRef.current = performance.now();
    progress.set(0);

    const tick = () => {
      if (!hoverStartRef.current) return;
      const elapsed = performance.now() - hoverStartRef.current;
      const p = Math.min(elapsed / FILL_DURATION, 1);
      progress.set(p);

      if (p >= 1) {
        navigatedRef.current = true;
        router.push("/guides?type=tutorial");
        return;
      }
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
  }, [progress, router]);

  const stopFill = useCallback(() => {
    hoverStartRef.current = null;
    if (rafRef.current) cancelAnimationFrame(rafRef.current);
    animate(progress, 0, { duration: 0.3 });
  }, [progress]);

  // React to browser hover changes
  useEffect(() => {
    if (browserHovering) {
      startFill();
    } else if (!selfHovering) {
      stopFill();
    }
  }, [browserHovering, selfHovering, startFill, stopFill]);

  const handleEnter = useCallback(() => {
    setSelfHovering(true);
    onHoverChange?.(true);
    startFill();
  }, [startFill, onHoverChange]);

  const handleLeave = useCallback(() => {
    setSelfHovering(false);
    onHoverChange?.(false);
    if (!browserHovering) stopFill();
  }, [browserHovering, stopFill, onHoverChange]);

  useEffect(() => {
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
    };
  }, []);

  return (
    <div className="flex flex-wrap items-center gap-3">
      {/* Watch tutorials — green progress bar fills over violet base */}
      <div
        onMouseEnter={handleEnter}
        onMouseLeave={handleLeave}
        className="relative inline-flex items-center rounded-full bg-violet-600 shadow-md shadow-violet-500/30 hover:shadow-violet-500/50 transition-shadow duration-200 overflow-hidden cursor-pointer select-none"
        onClick={() => router.push("/guides?type=tutorial")}
      >
        {/* Green fill that sweeps left-to-right */}
        <motion.div
          className="absolute inset-0 bg-green-500 origin-left rounded-full"
          style={{ scaleX: smoothProgress }}
        />
        <span className="relative z-10 px-6 py-3 sm:px-8 sm:py-4 text-base sm:text-lg font-semibold text-white whitespace-nowrap inline-flex items-center gap-2">
          Watch tutorials
          <ArrowRight size={18} />
        </span>
      </div>

      {/* Try for free — blue */}
      <button
        onClick={() => router.push("/signup")}
        className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-6 py-3 sm:px-8 sm:py-4 text-base sm:text-lg font-semibold text-white shadow-md shadow-blue-500/30 hover:bg-blue-700 hover:shadow-blue-500/50 active:scale-95 transition-all duration-200"
      >
        Try for free
        <ArrowRight size={18} />
      </button>
    </div>
  );
};
