"use client";

import { useState, useRef, useCallback, useEffect } from "react";
import { motion, useMotionValue, useSpring } from "framer-motion";
import { useRouter } from "next/navigation";
import { useIsMobile } from "@/hooks/use-mobile";
import { ArrowRight, ArrowDown, Play } from "lucide-react";
import { AnimatePresence } from "framer-motion";

const BROWSER_WIDTH = 820;
// Resting: 50% hidden off-screen right
const RESTING_X = BROWSER_WIDTH * 0.40;
// Hovered: slight portion still off-screen
const HOVERED_X = BROWSER_WIDTH * 0.08;

// Single concatenated loop of key feature recordings.
// Generated by: npm run record:shortlist
// Hosted in Supabase Storage (videos bucket) — uploaded via scripts/upload-videos.ts
const HERO_VIDEO = `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/videos/hero-loop.mp4`;

export const HeroBrowser = ({
  onHoverChange,
  ctaHovering,
}: {
  onHoverChange?: (hovering: boolean) => void;
  ctaHovering?: boolean;
}) => {
  const isMobile = useIsMobile();
  const router = useRouter();
  const [selfHovering, setSelfHovering] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);

  // Slide offset as a motion value so we can spring it
  const slideX = useMotionValue(RESTING_X);
  const springX = useSpring(slideX, { stiffness: 200, damping: 24 });

  const isHovered = selfHovering || !!ctaHovering;

  // Pull out or retract based on combined hover state
  useEffect(() => {
    slideX.set(isHovered ? HOVERED_X : RESTING_X);
  }, [isHovered, slideX]);

  // Half speed at rest, full speed when hovered
  useEffect(() => {
    if (videoRef.current) {
      videoRef.current.playbackRate = isHovered ? 1 : 0.5;
    }
  }, [isHovered]);

  const handleEnter = useCallback(() => {
    setSelfHovering(true);
    onHoverChange?.(true);
  }, [onHoverChange]);

  const handleLeave = useCallback(() => {
    setSelfHovering(false);
    onHoverChange?.(false);
  }, [onHoverChange]);

  if (isMobile) return null;

  return (
    <motion.div
      onMouseEnter={handleEnter}
      onMouseLeave={handleLeave}
      onClick={() => router.push("/guides?type=tutorial")}
      className="absolute right-0 top-1/2 z-[5] cursor-pointer"
      style={{
        width: BROWSER_WIDTH,
        x: springX,
        y: "-50%",
      }}
      initial={{ opacity: 0, x: BROWSER_WIDTH }}
      animate={{ opacity: 1, x: RESTING_X }}
      transition={{ type: "spring", stiffness: 80, damping: 18, delay: 0.6 }}
    >
      {/* Browser frame */}
      <div className="relative rounded-xl border border-border/60 bg-card shadow-2xl overflow-hidden">
        {/* Title bar */}
        <div className="flex items-center gap-2 px-4 py-3 bg-muted/80 border-b border-border/40">
          {/* macOS dots */}
          <div className="flex items-center gap-1.5">
            <div className="w-3 h-3 rounded-full bg-[#ff5f57]" />
            <div className="w-3 h-3 rounded-full bg-[#febc2e]" />
            <div className="w-3 h-3 rounded-full bg-[#28c840]" />
          </div>
          {/* Address bar */}
          <div className="flex-1 mx-3">
            <div className="bg-background/60 rounded-md px-3 py-1 text-xs text-muted-foreground font-mono truncate">
              app.useprompt.co.uk/dashboard
            </div>
          </div>
        </div>

        {/* Content area — video preview */}
        <div className="relative aspect-[16/9] bg-background overflow-hidden">
          {/* Video dims slightly at rest */}
          <motion.div
            className="w-full h-full"
            animate={{ opacity: isHovered ? 1 : 0.5 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
          >
            <video
              ref={videoRef}
              src={HERO_VIDEO}
              className="w-full h-full object-cover"
              muted
              autoPlay
              loop
              playsInline
            />
          </motion.div>
          {/* Frosted glass overlay — always visible */}
          <div className="absolute inset-0 backdrop-blur-[2px] pointer-events-none" />
          {/* CTA overlay — fades in when browser is expanded */}
          <AnimatePresence>
            {isHovered && (
              <motion.div
                className="absolute inset-0 flex items-center justify-center pointer-events-none"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.3, ease: "easeOut" }}
              >
                <div className="inline-flex items-center gap-2 rounded-full bg-white/90 backdrop-blur-sm px-5 py-2.5 text-sm font-semibold text-foreground shadow-lg shadow-black/10">
                  <Play size={14} className="fill-current" />
                  See tutorials
                </div>
              </motion.div>
            )}
          </AnimatePresence>
          {/* Subtle gradient overlay on the left edge for smooth page blend */}
          <div className="absolute inset-y-0 left-0 w-16 bg-gradient-to-r from-background/40 to-transparent pointer-events-none" />
        </div>
      </div>
    </motion.div>
  );
};

/**
 * CTA buttons: "Find out more" scrolls to #features + "Try for free" goes to signup.
 */
export const HeroCta = ({
  browserHovering,
  onHoverChange,
}: {
  browserHovering: boolean;
  onHoverChange?: (hovering: boolean) => void;
}) => {
  const router = useRouter();

  return (
    <div className="flex flex-wrap items-center gap-3">
      {/* Find out more — scrolls to features section */}
      <button
        onClick={() => {
          const el = document.getElementById("features");
          if (el) el.scrollIntoView({ behavior: "smooth" });
        }}
        className="inline-flex items-center gap-2 rounded-full bg-violet-600 px-6 py-3 sm:px-8 sm:py-4 text-base sm:text-lg font-semibold text-white shadow-md shadow-violet-500/30 hover:bg-violet-700 hover:shadow-violet-500/50 active:scale-95 transition-all duration-200"
      >
        Find out more
        <ArrowDown size={18} />
      </button>

      {/* Try for free — blue */}
      <button
        onClick={() => router.push("/signup")}
        className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-6 py-3 sm:px-8 sm:py-4 text-base sm:text-lg font-semibold text-white shadow-md shadow-blue-500/30 hover:bg-blue-700 hover:shadow-blue-500/50 active:scale-95 transition-all duration-200"
      >
        Try for free
        <ArrowRight size={18} />
      </button>
    </div>
  );
};
