/**
 * Hydrate demo data with actual files and email bodies.
 *
 * 1. Generates placeholder PDFs for all client_documents that have a storage_path
 *    but no actual file in Supabase Storage. Each PDF contains the document filename,
 *    client name, and filing type as visible text.
 *
 * 2. Creates reminder_queue entries with rendered email body content for all
 *    email_log entries that have no reminder_queue_id, then links them.
 *
 * Idempotent: skips documents that already have files and emails that already have bodies.
 * Run via: npx tsx scripts/demo/hydrate-demo-files.ts
 */

import { createClient } from "@supabase/supabase-js";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import * as dotenv from "dotenv";
import { resolve } from "path";
import crypto from "crypto";

dotenv.config({ path: resolve(process.cwd(), ".env.local") });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const BUCKET_NAME = process.env.SUPABASE_STORAGE_BUCKET_DOCUMENTS ?? "prompt-documents";

if (!supabaseUrl || !supabaseServiceKey) {
  console.error(
    "Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local"
  );
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: { autoRefreshToken: false, persistSession: false },
});

// ─── Filing type display labels ─────────────────────────────────────────────

const FILING_LABELS: Record<string, string> = {
  corporation_tax_payment: "Corporation Tax Payment",
  ct600_filing: "CT600 Filing",
  companies_house: "Companies House Annual Return",
  vat_return: "VAT Return",
  self_assessment: "Self Assessment",
  confirmation_statement: "Confirmation Statement",
  sa_payment_on_account: "SA Payment on Account",
  mtd_quarterly_update: "MTD Quarterly Update",
};

// ─── PDF generation ─────────────────────────────────────────────────────────

async function generatePlaceholderPdf(
  filename: string,
  clientName: string,
  filingType: string,
  source: string,
  dateStr: string
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]); // A4
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const filingLabel = FILING_LABELS[filingType] ?? filingType;
  const { height } = page.getSize();

  // Light grey background header area
  page.drawRectangle({
    x: 0,
    y: height - 160,
    width: 595,
    height: 160,
    color: rgb(0.96, 0.96, 0.96),
  });

  // Title
  page.drawText(filename, {
    x: 50,
    y: height - 70,
    size: 22,
    font: fontBold,
    color: rgb(0.1, 0.1, 0.1),
  });

  // Subtitle
  page.drawText(`${clientName} — ${filingLabel}`, {
    x: 50,
    y: height - 100,
    size: 14,
    font,
    color: rgb(0.35, 0.35, 0.35),
  });

  // Metadata line
  page.drawText(`Source: ${source}  •  Date: ${dateStr}`, {
    x: 50,
    y: height - 125,
    size: 10,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  // Divider
  page.drawLine({
    start: { x: 50, y: height - 180 },
    end: { x: 545, y: height - 180 },
    thickness: 0.5,
    color: rgb(0.8, 0.8, 0.8),
  });

  // Body placeholder text
  const bodyLines = [
    "This is a placeholder document generated for demo purposes.",
    "",
    `This file represents a ${filingLabel} document for ${clientName}.`,
    "In a live environment, this would contain the actual document content",
    "uploaded by the client or prepared by the accountant.",
    "",
    "Document Details:",
    `  Filing Type:    ${filingLabel}`,
    `  Client:         ${clientName}`,
    `  Original File:  ${filename}`,
    `  Upload Source:   ${source === "portal_upload" ? "Client Portal" : source === "inbound_email" ? "Inbound Email" : "Manual Upload"}`,
    "",
    "--------------------------------------------",
    "",
    "DEMO DATA — NOT A REAL DOCUMENT",
  ];

  let y = height - 210;
  for (const line of bodyLines) {
    page.drawText(line, {
      x: 50,
      y,
      size: 11,
      font: line.startsWith("  ") ? font : line === bodyLines[0] ? fontBold : font,
      color: line.includes("DEMO DATA") ? rgb(0.7, 0.2, 0.2) : rgb(0.2, 0.2, 0.2),
    });
    y -= 18;
  }

  // Footer
  page.drawText("Generated by Prompt demo data hydration script", {
    x: 50,
    y: 40,
    size: 8,
    font,
    color: rgb(0.6, 0.6, 0.6),
  });

  return doc.save();
}

// ─── Email body generation ──────────────────────────────────────────────────

function generateEmailBody(
  clientName: string,
  filingType: string,
  subject: string,
  recipientEmail: string,
  orgName: string
): { text: string; html: string } {
  const filingLabel = FILING_LABELS[filingType] ?? filingType;

  const text = [
    `Dear ${clientName},`,
    "",
    `This is a reminder that your ${filingLabel} deadline is approaching.`,
    "",
    "We wanted to check in and remind you that we still need the following",
    "records from you in order to complete this filing on time:",
    "",
    "  • Latest management accounts or trial balance",
    "  • Bank statements for the relevant period",
    "  • Any additional supporting documentation",
    "",
    "Please upload these documents through your secure client portal at your",
    "earliest convenience, or reply to this email if you have any questions.",
    "",
    "If you have already sent these documents, please disregard this reminder.",
    "",
    "Kind regards,",
    orgName,
  ].join("\n");

  const html = `
<div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px 24px; color: #1a1a1a;">
  <p style="margin: 0 0 16px;">Dear ${clientName},</p>
  <p style="margin: 0 0 16px;">This is a reminder that your <strong>${filingLabel}</strong> deadline is approaching.</p>
  <p style="margin: 0 0 8px;">We wanted to check in and remind you that we still need the following records from you in order to complete this filing on time:</p>
  <ul style="margin: 8px 0 16px; padding-left: 24px; color: #333;">
    <li style="margin-bottom: 4px;">Latest management accounts or trial balance</li>
    <li style="margin-bottom: 4px;">Bank statements for the relevant period</li>
    <li style="margin-bottom: 4px;">Any additional supporting documentation</li>
  </ul>
  <p style="margin: 0 0 16px;">Please upload these documents through your secure client portal at your earliest convenience, or reply to this email if you have any questions.</p>
  <p style="margin: 0 0 16px; color: #666;">If you have already sent these documents, please disregard this reminder.</p>
  <p style="margin: 24px 0 0;">Kind regards,<br/><strong>${orgName}</strong></p>
</div>`.trim();

  return { text, html };
}

// ─── Main ───────────────────────────────────────────────────────────────────

async function hydrate() {
  console.log("=== Hydrating Demo Data ===\n");

  // ── 1. Upload placeholder files for documents ────────────────────────────

  console.log("1. Uploading placeholder files for client_documents...\n");

  // Get all documents with a storage_path
  const { data: docs, error: docsError } = await supabase
    .from("client_documents")
    .select(`
      id,
      storage_path,
      original_filename,
      filing_type_id,
      source,
      created_at,
      client_id,
      clients ( company_name )
    `)
    .not("storage_path", "is", null);

  if (docsError) {
    console.error("  Failed to fetch documents:", docsError.message);
  } else if (!docs || docs.length === 0) {
    console.log("  No documents found with storage paths.");
  } else {
    let uploaded = 0;
    let skipped = 0;

    for (const doc of docs) {
      const storagePath = doc.storage_path as string;
      const clientName = (doc.clients as any)?.company_name ?? "Unknown Client";
      const ext = doc.original_filename?.split(".").pop()?.toLowerCase();

      // Check if file already exists in storage
      const { data: existingFile } = await supabase.storage
        .from(BUCKET_NAME)
        .download(storagePath);

      if (existingFile && existingFile.size > 0) {
        skipped++;
        continue;
      }

      // Generate appropriate file based on extension
      let fileBytes: Uint8Array;
      let contentType: string;

      if (ext === "pdf") {
        fileBytes = await generatePlaceholderPdf(
          doc.original_filename,
          clientName,
          doc.filing_type_id,
          doc.source ?? "manual",
          new Date(doc.created_at).toLocaleDateString("en-GB")
        );
        contentType = "application/pdf";
      } else if (ext === "xlsx" || ext === "xls") {
        // For spreadsheets, generate a PDF anyway — the preview modal can't
        // display xlsx, but having a file prevents the "no file" error.
        // Mark the storage_path to .pdf isn't right — instead just upload a
        // small placeholder so the download button works.
        fileBytes = await generatePlaceholderPdf(
          doc.original_filename,
          clientName,
          doc.filing_type_id,
          doc.source ?? "manual",
          new Date(doc.created_at).toLocaleDateString("en-GB")
        );
        contentType = "application/pdf";
        // Update the storage_path to .pdf so preview works
        const pdfPath = storagePath.replace(/\.(xlsx|xls)$/, ".pdf");
        const { error: uploadError } = await supabase.storage
          .from(BUCKET_NAME)
          .upload(pdfPath, fileBytes, {
            contentType,
            upsert: true,
          });
        if (uploadError) {
          console.error(`  ✗ ${doc.original_filename}: ${uploadError.message}`);
        } else {
          // Update the DB record to point to the new PDF path
          await supabase
            .from("client_documents")
            .update({ storage_path: pdfPath })
            .eq("id", doc.id);
          uploaded++;
          console.log(`  ✓ ${doc.original_filename} → ${pdfPath} (${clientName})`);
        }
        continue;
      } else {
        // Other file types — generate a PDF placeholder
        fileBytes = await generatePlaceholderPdf(
          doc.original_filename,
          clientName,
          doc.filing_type_id,
          doc.source ?? "manual",
          new Date(doc.created_at).toLocaleDateString("en-GB")
        );
        contentType = "application/pdf";
      }

      const { error: uploadError } = await supabase.storage
        .from(BUCKET_NAME)
        .upload(storagePath, fileBytes, {
          contentType,
          upsert: true,
        });

      if (uploadError) {
        console.error(`  ✗ ${doc.original_filename}: ${uploadError.message}`);
      } else {
        uploaded++;
        console.log(`  ✓ ${doc.original_filename} (${clientName})`);
      }
    }

    console.log(`\n  Uploaded: ${uploaded}, Already existed: ${skipped}, Total: ${docs.length}`);
  }

  // ── 2. Hydrate email bodies for email_log entries ────────────────────────

  console.log("\n2. Hydrating email bodies for email_log entries...\n");

  // Find email_log entries without a reminder_queue_id
  const { data: orphanedEmails, error: emailError } = await supabase
    .from("email_log")
    .select(`
      id,
      client_id,
      filing_type_id,
      recipient_email,
      subject,
      sent_at,
      send_type,
      org_id,
      clients ( company_name )
    `)
    .is("reminder_queue_id", null);

  if (emailError) {
    console.error("  Failed to fetch email logs:", emailError.message);
  } else if (!orphanedEmails || orphanedEmails.length === 0) {
    console.log("  No orphaned email_log entries found.");
  } else {
    // Get the org name for email signatures
    const orgIds = [...new Set(orphanedEmails.map((e) => e.org_id).filter(Boolean))];
    const orgNames: Record<string, string> = {};
    for (const oid of orgIds) {
      const { data: org } = await supabase
        .from("organisations")
        .select("name")
        .eq("id", oid)
        .single();
      if (org) orgNames[oid] = org.name;
    }

    let hydrated = 0;

    for (const email of orphanedEmails) {
      const clientName = (email.clients as any)?.company_name ?? "Client";
      const orgName = orgNames[email.org_id] ?? "Your Accountant";
      const filingType = email.filing_type_id ?? "corporation_tax_payment";

      const { text, html } = generateEmailBody(
        clientName,
        filingType,
        email.subject,
        email.recipient_email,
        orgName
      );

      // Create a reminder_queue entry with the rendered body
      const queueId = crypto.randomUUID();
      const { error: queueError } = await supabase
        .from("reminder_queue")
        .insert({
          id: queueId,
          client_id: email.client_id,
          filing_type_id: filingType,
          template_id: null,
          step_index: 0,
          deadline_date: new Date(
            new Date(email.sent_at).getTime() + 14 * 86400000
          )
            .toISOString()
            .split("T")[0],
          send_date: new Date(email.sent_at).toISOString().split("T")[0],
          status: "sent",
          resolved_subject: email.subject,
          resolved_body: text,
          html_body: html,
          org_id: email.org_id,
        });

      if (queueError) {
        console.error(
          `  ✗ Email to ${clientName}: ${queueError.message}`
        );
        continue;
      }

      // Link the email_log entry to the new queue entry
      const { error: linkError } = await supabase
        .from("email_log")
        .update({ reminder_queue_id: queueId })
        .eq("id", email.id);

      if (linkError) {
        console.error(
          `  ✗ Failed to link email ${email.id}: ${linkError.message}`
        );
      } else {
        hydrated++;
        console.log(`  ✓ ${email.subject} → ${clientName}`);
      }
    }

    console.log(`\n  Hydrated: ${hydrated} / ${orphanedEmails.length} email bodies`);
  }

  console.log("\n=== Done ===");
}

hydrate().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
