#!/usr/bin/env bash

# New Practice Setup Script
# Usage: ./scripts/setup-new-practice.sh "Practice Name"

set -e

PRACTICE_NAME="${1:-New Practice}"

echo "=== New Practice Setup: $PRACTICE_NAME ==="
echo ""

echo "Step 1: Create Supabase Project"
echo "  - Go to https://supabase.com/dashboard"
echo "  - Create new project (use lowercase, hyphenated name like 'peninsula-smithco')"
echo "  - Region: EU West (London) recommended for UK practices"
echo "  - Note down:"
echo "    * Project URL (looks like: https://PROJECT_REF.supabase.co)"
echo "    * Anon key (starts with 'eyJ...')"
echo "    * Service role key (starts with 'eyJ...')"
echo ""

echo "Step 2: Link and Run Migrations"
echo "  After creating the project, run:"
echo "    npx supabase link --project-ref <PROJECT_REF>"
echo "    npx supabase db push"
echo ""
echo "  This will create all tables, RLS policies, and constraints."
echo ""

echo "Step 3: Create Demo User (Optional - for prospect evaluation)"
echo "  In Supabase Dashboard > Authentication > Users:"
echo "  - Click 'Add User'"
echo "  - Email: demo@peninsula-internal.local"
echo "  - Password: demo-peninsula-2026-secure"
echo "  - Mark 'Auto Confirm User' (check the box)"
echo "  - This allows prospects to try the system without QuickBooks OAuth"
echo "  - Demo users share the same dataset (expected behavior)"
echo ""

echo "Step 4: Configure QuickBooks OAuth Application"
echo "  - Register app at https://developer.intuit.com"
echo "  - Create new app or add redirect URL to existing app"
echo "  - Set redirect URL to: https://<practice-domain>/onboarding/callback"
echo "  - Note Client ID and Client Secret for environment variables"
echo ""

echo "Step 5: Deploy to Vercel"
echo "  Option A - New Vercel project (recommended for separate domain):"
echo "    vercel --yes"
echo ""
echo "  Option B - Add environment to existing project:"
echo "    Set environment variables in Vercel dashboard for this practice"
echo ""

echo "Step 6: Set Environment Variables (in Vercel)"
echo "  Required variables:"
echo "    NEXT_PUBLIC_SUPABASE_URL=<from step 1>"
echo "    NEXT_PUBLIC_SUPABASE_ANON_KEY=<from step 1>"
echo "    SUPABASE_SERVICE_ROLE_KEY=<from step 1>"
echo "    POSTMARK_SERVER_TOKEN=<shared or practice-specific>"
echo "    QUICKBOOKS_CLIENT_ID=<from step 3>"
echo "    QUICKBOOKS_CLIENT_SECRET=<from step 3>"
echo "    QUICKBOOKS_REDIRECT_URI=https://<practice-domain>/onboarding/callback"
echo ""

# Generate CRON_SECRET
CRON_SECRET=$(openssl rand -base64 32 2>/dev/null || echo "GENERATE_MANUALLY")
echo "  Generated CRON_SECRET: $CRON_SECRET"
echo "    CRON_SECRET=$CRON_SECRET"
echo ""

echo "Step 7: Configure Postmark (if practice-specific sender)"
echo "  - Add practice domain to Postmark account"
echo "  - Set up DKIM and return-path DNS records"
echo "  - Verify domain in Postmark"
echo "  - Or use shared Postmark account with verified sender signature"
echo ""


echo "Step 8: Configure Vercel Cron (for reminder automation)"
echo "  - Go to Vercel project > Settings > Cron Jobs"
echo "  - Add cron job:"
echo "    Path: /api/cron/reminders"
echo "    Schedule: 0 9 * * * (9am daily, or customize)"
echo "  - Add another cron job:"
echo "    Path: /api/cron/send-emails"
echo "    Schedule: */15 * * * * (every 15 minutes)"
echo "  - Ensure CRON_SECRET is set in environment variables"
echo ""

echo "Step 9: First Login and Onboarding"
echo "  - User visits the deployed URL"
echo "  - Login page shows two options:"
echo "    * 'Sign in with QuickBooks' (for real practice usage)"
echo "    * 'Try Demo' (for prospect evaluation without QuickBooks)"
echo ""
echo "  QuickBooks Login Flow:"
echo "  - Click 'Sign in with QuickBooks' and complete OAuth"
echo "  - System automatically:"
echo "    * Creates Supabase Auth user (using QuickBooks company ID)"
echo "    * Stores QuickBooks OAuth tokens"
echo "    * Syncs client list from QuickBooks"
echo "    * Redirects to onboarding wizard"
echo "  - Complete onboarding (configure clients, set email sender)"
echo "  - Reach dashboard with live QuickBooks data"
echo ""
echo "  Demo Login Flow:"
echo "  - Click 'Try Demo' button"
echo "  - Automatically signs in with shared demo account"
echo "  - Redirects to dashboard/onboarding with sample data"
echo "  - No QuickBooks connection required"
echo ""

echo "Step 10: Verify Setup"
echo "  - Dashboard should show synced clients"
echo "  - Verify cron is running (check Vercel Cron tab after 24 hours)"
echo "  - Check that reminders are being queued"
echo ""

echo "=== Setup Complete ==="
echo ""
echo "Environment Variables Template (.env.local for reference):"
echo "---"
echo "NEXT_PUBLIC_SUPABASE_URL=https://YOUR_PROJECT_REF.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJ..."
echo "SUPABASE_SERVICE_ROLE_KEY=eyJ..."
echo "CRON_SECRET=$CRON_SECRET"
echo "POSTMARK_SERVER_TOKEN=your_postmark_token"
echo "QUICKBOOKS_CLIENT_ID=your_qb_client_id"
echo "QUICKBOOKS_CLIENT_SECRET=your_qb_client_secret"
echo "QUICKBOOKS_REDIRECT_URI=https://your-domain.com/onboarding/callback"
echo "---"
echo ""
echo "Documentation:"
echo "  - Multi-tenancy decision: MULTI-TENANCY.md"
echo "  - Project overview: .planning/PROJECT.md"
echo "  - Deadline formulas: .planning/DEADLINE-VAT-ANALYSIS.md"
echo ""
